import {
  object,
  string,
  boolean,
  nullable,
  integer,
  number,
  nonempty,
  optional,
} from 'superstruct'

export const struct = object({
  id: optional(integer()),
  productTypeId: nullable(integer()),
  threads: nullable(integer()),
  contents: nullable(integer()),
  fleece: nullable(boolean()),
  name: nonempty(string()),
  price: integer(),
  dollarPrice: nullable(number()),
  dollarRate: nullable(number()),
  weight: nullable(number()),
  width: nullable(integer()),
  density: nullable(integer()),
  widthShop: nullable(integer()),
  densityShop: nullable(integer()),
  weightForCount: nullable(integer()),
  lengthForCount: nullable(number()),
  pricePre: nullable(integer()),
  image: string(),
})
